# Generated by Django 4.2.5 on 2023-10-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=True, upload_to='category_images'),
        ),
    ]
