# Generated by Django 4.2.5 on 2023-10-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_payment_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbuy',
            name='product',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='website.product'),
        ),
    ]
