# Generated by Django 4.2.5 on 2023-10-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_productbuy_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbuy',
            name='category',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
    ]
