# Generated by Django 4.2.5 on 2023-10-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbuy',
            name='modeofpayment',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='website.payment'),
        ),
        migrations.AlterField(
            model_name='productbuy',
            name='product',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='website.product'),
        ),
    ]
