# Generated by Django 4.2.5 on 2023-10-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_productbuy_modeofpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbuy',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
    ]
