# Generated by Django 4.2.5 on 2023-10-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbuy',
            name='contactno',
            field=models.CharField(max_length=10),
        ),
    ]
